amp_opt_level: 1
assume_yes: false
base_lr: 0.01
batch_size: 32
checkpoint: null
config: ./config/nturgbd-cross-subject/test_joint_msg3d_ssnet.yaml
debug: false
device:
- 0
eval_interval: 1
eval_start: 1
feeder: feeders.pku_feeder2.Feeder
forward_batch_size: 16
half: false
ignore_weights: []
log_interval: 100
model: model.msg3d2.Model
model_args:
  graph: graph.ntu_rgb_d.AdjMatrixGraph
  num_class: 60
  num_g3d_scales: 6
  num_gcn_scales: 13
  num_person: 2
  num_point: 25
model_saved_name: ''
nesterov: false
num_epoch: 80
num_worker: 32
optimizer: SGD
optimizer_states: null
phase: test
print_log: true
save_interval: 1
save_score: true
seed: 93
show_topk:
- 1
- 5
start_epoch: 0
step:
- 20
- 40
- 60
test_batch_size: 1
test_feeder_args:
  data_dir: /home/user/Annisa/MS-G3D/data/pkummd/Data/PKU_Skeleton_Renew
  debug: false
  label_agg: last
  label_dir: /home/user/Annisa/MS-G3D/data/pkummd/Label
  length_dir: /home/user/Annisa/MS-G3D/data/pkummd/Length
  mode: val
  pitch: 0
  roll: 0
  split_path: /home/user/Annisa/MS-G3D/data/pkummd/Split/cross-subject.txt
  stride: 1
  window_size: 255
  yaw: 0
train_feeder_args: {}
weight_decay: 0.0005
weights: ./work_dir/pkummd/msg3d_ssnet/weights/weights-46-134412.pt
work_dir: ./eval/pku/msg3d_ssnet2
